NEXT-39569 - Sync license host
shopware/service-bundle-symfony pull request #24
Opened 2024-11-14 07:50 UTC by nam4am

2024-11-14 11:34 UTC, nam4am commented on src/Controller/LicenseController.php
> +        if ($licenseHost) {
should allow upsert licenseHot to null

2024-11-14 14:20 UTC, AydinHassan requested changes

2024-11-14 14:20 UTC, AydinHassan commented on src/Controller/LicenseController.php
> +            return $this->createErrorResponse('missing_license_key', 'No license key or license host provided', Response::HTTP_BAD_REQUEST);
maybe update type aswell?

2024-11-15 09:29 UTC, AydinHassan commented on tests/Controller/LicenseControllerTest.php
> +    public function testSyncWithValidLicenseHost(): void
Maybe a test with both just for completeness? But i approve anyway, so merge when you want

2024-11-15 09:29 UTC, AydinHassan approved these changes

2024-11-18 01:17 UTC, merged